---
apiVersion: batch/v1
kind: Job
metadata:
  name: calrissian-remzi-job
spec:
  template:
    spec:
      containers:
      - name: calrissian
        image: dukegcb/calrissian:latest
        command: ["calrissian"]
        args:
          - "--default-container"
          - "docker"
          - "--stdout"
          - "/data/output-data/output.json"
          - "--stderr"
          - "/data/output-data/stderr.log"
          - "--max-ram"
          - "16G"
          - "--max-cores"
          - "8"
          - "--tmp-outdir-prefix"
          - "/data/tmpout/"
          - "--outdir"
          - "/data/output-data/"
          - "--usage-report"
          - "/data/output-data/usage.json"
          - "/data/FaVLib/workflow/main-workflow-aynec.cwl"
          - "/data/FaVLib/workflow/workflow-aynec.yml"
        volumeMounts:
        - mountPath: /data
          name: pv-test-vincent
          subPath: calrissian-remzi
        env:
        - name: CALRISSIAN_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      restartPolicy: Never
      volumes:
      - name: pv-test-vincent
        persistentVolumeClaim:
          claimName: pvc-mapr-projects-test-vincent